datasets:
  rsicd_caption: # name of the dataset builder
    dataset_card: dataset_card/rsicd_caption.md
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Pre-training phase annotates away validation and test sets
      annotations:
        train:
          storage: /usr/data/RSIC/RSICD/annotations/RSICD_train.json
        # val:
        #   storage: /usr/data/RSIC/RSICD/annotations/RSICD_val.json
        # test:
        #   storage: /usr/data/RSIC/RSICD/annotations/RSICD_test.json
      images:
        storage: /usr/data/RSIC/RSICD/images/
