model:
  arch: pretrain
  load_finetuned: False

  pretrained: ""
  finetuned: ""

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True

  # Q-Former
  num_query_token: 32


preprocess:
    vis_processor:
        train:
          name: "bita_image_train"
          image_size: 224
        eval:
          name: "bita_image_eval"
          image_size: 224
    text_processor:
        train:
          name: "bita_caption"
        eval:
          name: "bita_caption"
